name: CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: 'output/'
          destination-github-username: 'self-driven-development'
          destination-repository-name: 'Dogsounds-TIL'
          user-name: github-actions[bot]
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main
          target-directory: docs/
          commit-message: 'Update TIL'
